### ISSUE TITLE
ValueError: slice index 0 of dimension 0 out of bounds.

### ISSUE THREAD

**Issue by Billy1900** [tensorflow/privacy#107]
# Version
Tensorflow version: 1.14.0
System version: Windows 10

# Problem Description
I use tensorflow/privacy in my code, as follows,

original code:
```
self.optimizer = tf.compat.v1.train.AdamOptimizer(learning_rate=args.learning_rate)
```
updated code
```
self.optimizer = dp_optimizer.DPAdamGaussianOptimizer(l2_norm_clip=4, noise_multiplier=sigma, learning_rate=args.learning_rate, ledger=None)

```
and stack
```
Traceback (most recent call last):
  File "D:\Anaconda\envs\tf14\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\Anaconda\envs\tf14\lib\site-packages\tensorflow\python\framework\ops.py", line 5652, in get_controller
    yield g
  File "D:\Anaconda\envs\tf14\lib\site-packages\tensorflow\python\ops\array_ops.py", line 680, in _slice_helper
    name=name)
  File "D:\Anaconda\envs\tf14\lib\site-packages\tensorflow\python\ops\array_ops.py", line 846, in strided_slice
    shrink_axis_mask=shrink_axis_mask)
  File "D:\Anaconda\envs\tf14\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 12095, in strided_slice
    shrink_axis_mask=shrink_axis_mask, name=name)
  File "D:\Anaconda\envs\tf14\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "D:\Anaconda\envs\tf14\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "D:\Anaconda\envs\tf14\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "D:\Anaconda\envs\tf14\lib\site-packages\tensorflow\python\framework\ops.py", line 2027, in __init__
    control_input_ops)
  File "D:\Anaconda\envs\tf14\lib\site-packages\tensorflow\python\framework\ops.py", line 1867, in _create_c_op
    raise ValueError(str(e))
```
And also I attach my code.
[gcn.zip](https://github.com/tensorflow/privacy/files/4671799/gcn.zip)

Hope anyone could help me with this

**Comment by Billy1900** [comment]
I solved the issue by myself. closed.
