### ISSUE TITLE
Cannot load the model trained in mnist_dpsgd_tutorial_keras.py

### ISSUE THREAD

**Issue by bigmoumou** [tensorflow/privacy#161]
I tried to run `mnist_dpsgd_tutorial_keras.py` code in tutorial, and saved the model with `model.save('./model.h5')` after training, but I got the following errors when I tried to load the model by `load_model('./model.h5')`. I'm using tensorflow-gpu==2.4.1 and tensorflow-privacy==0.5.1. Is saving privacy model require a different save method?

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda3\envs\dp-tf\lib\site-packages\tensorflow\python\keras\saving\save.py", line 207, in load_model
    compile)
  File "D:\Anaconda3\envs\dp-tf\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 200, in load_model_from_hdf5
    training_config, custom_objects))
  File "D:\Anaconda3\envs\dp-tf\lib\site-packages\tensorflow\python\keras\saving\saving_utils.py", line 212, in compile_args_from_training_config
    optimizer = optimizers.deserialize(optimizer_config)
  File "D:\Anaconda3\envs\dp-tf\lib\site-packages\tensorflow\python\keras\optimizers.py", line 87, in deserialize
    printable_module_name='optimizer')
  File "D:\Anaconda3\envs\dp-tf\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 347, in deserialize_keras_object
    config, module_objects, custom_objects, printable_module_name)
  File "D:\Anaconda3\envs\dp-tf\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 296, in class_and_config_for_serialized_keras_object
    raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
ValueError: Unknown optimizer: DPOptimizerClass
```

**Comment by bigmoumou** [comment]
Referring to [#56565801](https://stackoverflow.com/questions/54835331/how-do-i-load-a-keras-saved-model-with-custom-optimizer/56565801#56565801), I found that the model need to be re-compile with the non-official optimizer, or just using `compile=False` to do inference only.
