### ISSUE TITLE
Bolton DP is not running on Tensorflow 1.14.0

### ISSUE THREAD

**Issue by sharmi1206** [tensorflow/privacy#209]
Runing this :
https://github.com/tensorflow/privacy/blob/master/tutorials/bolton_tutorial.py

Traceback (most recent call last):
  File "/Users/shachatt1/Desktop/sharmi/books/My_book_responsible_ai/python_code/chapter4/privacy-master/tutorials/bolton_tutorial.py", line 18, in <module>
    from tensorflow_privacy.privacy.bolt_on import losses  # pylint: disable=wrong-import-position
  File "/opt/miniconda3/lib/python3.7/site-packages/tensorflow_privacy/__init__.py", line 30, in <module>
    from tensorflow_privacy import v1
  File "/opt/miniconda3/lib/python3.7/site-packages/tensorflow_privacy/v1/__init__.py", line 32, in <module>
    from tensorflow_privacy.privacy.estimators.v1.dnn import DNNClassifier as DNNClassifierV1
  File "/opt/miniconda3/lib/python3.7/site-packages/tensorflow_privacy/privacy/estimators/v1/dnn.py", line 19, in <module>
    from tensorflow_privacy.privacy.estimators.v1 import head as head_lib
  File "/opt/miniconda3/lib/python3.7/site-packages/tensorflow_privacy/privacy/estimators/v1/head.py", line 23, in <module>
    from tensorflow_estimator.python.estimator import model_fn
  File "/opt/miniconda3/lib/python3.7/site-packages/tensorflow_estimator/__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "/opt/miniconda3/lib/python3.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1.estimator import experimental
  File "/opt/miniconda3/lib/python3.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py", line 10, in <module>
    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
  File "/opt/miniconda3/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py", line 23, in <module>
    from tensorflow.python.feature_column import dense_features
ImportError: cannot import name 'dense_features' from 'tensorflow.python.feature_column' (/opt/miniconda3/lib/python3.7/site-packages/tensorflow/python/feature_column/__init__.py)

**Comment by sharmi1206** [comment]
On further installation of tensorflow_estimator==1.14.0rc0

the error changed to something else

AttributeError: module 'tensorflow_estimator.python.estimator.canned.head' has no attribute '_all_class_ids'
