### ISSUE TITLE
Error when reload mnist data and labels

### ISSUE THREAD

**Issue by an1006634493** [tensorflow/privacy#32]
When I run 'train_teachers.py' under Python3 for the first time, 
```python train_teachers.py --nb_teachers=100 --teacher_id=0 --dataset=mnist --max_steps=1000```
datas and labels are downloaded and loaded successfully. 
But when run for a second time, 
```python train_teachers.py --nb_teachers=100 --teacher_id=1 --dataset=mnist --max_steps=1000```
the error occur:
```
Traceback (most recent call last):
  File "train_teachers.py", line 102, in <module>
    tf.app.run()
  File "D:\Users\10066\Anaconda3\envs\nn\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "train_teachers.py", line 99, in main
    assert train_teacher(FLAGS.dataset, FLAGS.nb_teachers, FLAGS.teacher_id)
  File "train_teachers.py", line 60, in train_teacher
    train_data, train_labels, test_data, test_labels = input.ld_mnist()
  File "E:\privacy-master\research\pate_2017\input.py", line 421, in ld_mnist
    train_data = extract_mnist_data(local_urls[0], 60000, 28, 1)
  File "E:\privacy-master\research\pate_2017\input.py", line 285, in extract_mnist_data
    return np.load(file_obj)
  File "D:\Users\10066\Anaconda3\envs\nn\lib\site-packages\numpy\lib\npyio.py", line 416, in load
    magic = fid.read(N)
  File "D:\Users\10066\Anaconda3\envs\nn\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 132, in read
    pywrap_tensorflow.ReadFromStream(self._read_buf, length, status))
  File "D:\Users\10066\Anaconda3\envs\nn\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 100, in _prepare_value
    return compat.as_str_any(val)
  File "D:\Users\10066\Anaconda3\envs\nn\lib\site-packages\tensorflow\python\util\compat.py", line 107, in as_str_any
    return as_str(value)
  File "D:\Users\10066\Anaconda3\envs\nn\lib\site-packages\tensorflow\python\util\compat.py", line 80, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
```

I try to fix this error by making some change in `input.py`. Original code is:
```
def extract_mnist_data(filename, num_images, image_size, pixel_depth):
  """
  Extract the images into a 4D tensor [image index, y, x, channels].

  Values are rescaled from [0, 255] down to [-0.5, 0.5].
  """
  # if not os.path.exists(file):
  if not tf.gfile.Exists(filename+".npy"):
    with gzip.open(filename) as bytestream:
      bytestream.read(16)
      buf = bytestream.read(image_size * image_size * num_images)
      data = np.frombuffer(buf, dtype=np.uint8).astype(np.float32)
      data = (data - (pixel_depth / 2.0)) / pixel_depth
      data = data.reshape(num_images, image_size, image_size, 1)
      np.save(filename, data)
      return data
  else:
    with tf.gfile.Open(filename+".npy", mode='r') as file_obj:
      return np.load(file_obj)


def extract_mnist_labels(filename, num_images):
  """
  Extract the labels into a vector of int64 label IDs.
  """
  # if not os.path.exists(file):
  if not tf.gfile.Exists(filename+".npy"):
    with gzip.open(filename) as bytestream:
      bytestream.read(8)
      buf = bytestream.read(1 * num_images)
      labels = np.frombuffer(buf, dtype=np.uint8).astype(np.int32)
      np.save(filename, labels)
    return labels
  else:
    with tf.gfile.Open(filename+".npy", mode='r') as file_obj:
      return np.load(file_obj)
```
I delete judgements of existance, as follows:
```

def extract_mnist_data(filename, num_images, image_size, pixel_depth):
  """
  Extract the images into a 4D tensor [image index, y, x, channels].

  Values are rescaled from [0, 255] down to [-0.5, 0.5].
  """
  # if not os.path.exists(file):
  with gzip.open(filename) as bytestream:
    bytestream.read(16)
    buf = bytestream.read(image_size * image_size * num_images)
    data = np.frombuffer(buf, dtype=np.uint8).astype(np.float32)
    data = (data - (pixel_depth / 2.0)) / pixel_depth
    data = data.reshape(num_images, image_size, image_size, 1)
    np.save(filename, data)
    return data


def extract_mnist_labels(filename, num_images):
  """
  Extract the labels into a vector of int64 label IDs.
  """
  # if not os.path.exists(file):
  with gzip.open(filename) as bytestream:
    bytestream.read(8)
    buf = bytestream.read(1 * num_images)
    labels = np.frombuffer(buf, dtype=np.uint8).astype(np.int32)
    np.save(filename, labels)
    return labels
```
It could work, but I'm wondering what cause the error, and also not sure if there is any risk to make such changes.

**Comment by npapernot** [comment]
There is no risk in doing that (it just removes caching of the preprocessed data), I'll work on a fix and close the issue when it is merged
