### ISSUE TITLE
Python3 tutorial training fails: "ValueError: No variables provided"

### ISSUE THREAD

**Issue by carlini** [tensorflow/privacy#4]
Running the default tutorial with no arguments in Python 3.5, TF 1.12 gives the following error

```Traceback (most recent call last):                                                                                                                                                
  File "tutorials/mnist_dpsgd_tutorial.py", line 184, in <module>                                                                                                                 
    tf.app.run()                                                                                                                                                                  
  File "/home/ncarlini/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run                                                                    
    _sys.exit(main(argv))                                                                                                                                                         
  File "tutorials/mnist_dpsgd_tutorial.py", line 169, in main                                                                                                                     
    mnist_classifier.train(input_fn=train_input_fn, steps=steps_per_epoch)                                                                                                        
  File "/home/ncarlini/.local/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train                                                           
    loss = self._train_model(input_fn, hooks, saving_listeners)                                                                                                                   
  File "/home/ncarlini/.local/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model                                                   
    return self._train_model_default(input_fn, hooks, saving_listeners)                                                                                                           
  File "/home/ncarlini/.local/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1237, in _train_model_default                                           
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)                                                                                                                   
  File "/home/ncarlini/.local/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn                                                 
    model_fn_results = self._model_fn(features=features, **kwargs)                                                                                                                
  File "tutorials/mnist_dpsgd_tutorial.py", line 86, in cnn_model_fn                                                                                                              
    train_op = optimizer.minimize(loss=vector_loss, global_step=global_step)                                                                                                      
  File "/home/ncarlini/.local/lib/python3.5/site-packages/tensorflow/python/training/optimizer.py", line 410, in minimize                                                         
    name=name)                                                                                                                                                                    
  File "/home/ncarlini/.local/lib/python3.5/site-packages/tensorflow/python/training/optimizer.py", line 570, in apply_gradients                                                  
    raise ValueError("No variables provided.")                                                                                                                                    
ValueError: No variables provided.
```

**Comment by lgondara** [comment]
I think changing line 92 in dp_optimizer.py to `return list(zip(final_grads, var_list))` should fix this.

**Comment by malzantot** [comment]
Had the same problem while using the DPOptimizer on my own model. The update highlighted by @lgondara  fixed it for me.
