### ISSUE TITLE
Problem with training keras model with DP optimizer

### ISSUE THREAD

**Issue by minxueric** [tensorflow/privacy#68]
The DP optimizer failed when training a tf.Keras model. Could you please help me solve the problem?

Anaconda3-5.3.1
Tensorflow 1.14.0

```python
Traceback (most recent call last):
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/mimic3-benchmarks/mimic3models/in_hospital_mortality/main.py", line 203, in <module>
    batch_size=args.batch_size)
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 780, in fit
    steps_name='steps_per_epoch')
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 157, in model_iteration
    f = _make_execution_function(model, mode)
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 532, in _make_execution_function
    return model._make_execution_function(mode)
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2276, in _make_execution_function
    self._make_train_function()
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2219, in _make_train_function
    params=self._collected_trainable_weights, loss=self.total_loss)
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/tensorflow/python/keras/optimizers.py", line 751, in get_updates
    grads = self.optimizer.compute_gradients(loss, params)
  File "/root/privacy/privacy/optimizers/dp_optimizer.py", line 172, in compute_gradients
    _, sample_state = tf.while_loop(cond_fn, body_fn, [idx, sample_state])
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3501, in while_loop
    return_same_structure)
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3012, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2937, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/root/privacy/privacy/optimizers/dp_optimizer.py", line 170, in <lambda>
    body_fn = lambda i, state: [tf.add(i, 1), process_microbatch(i, state)]  # pylint: disable=line-too-long
  File "/root/privacy/privacy/optimizers/dp_optimizer.py", line 146, in process_microbatch
    aggregation_method, colocate_gradients_with_ops, grad_loss))
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/tensorflow/python/training/optimizer.py", line 512, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/tensorflow/python/ops/gradients_impl.py", line 158, in gradients
    unconnected_gradients)
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/tensorflow/python/ops/gradients_util.py", line 617, in _GradientsHelper
    to_ops, from_ops, colocate_gradients_with_ops, func_graphs, xs)
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/tensorflow/python/ops/gradients_util.py", line 175, in _PendingCount
    between_op_list, between_ops, colocate_gradients_with_ops)
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1328, in MaybeCreateControlFlowState
    loop_state.AddWhileContext(op, between_op_list, between_ops)
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1137, in AddWhileContext
    grad_state = GradLoopState(forward_ctxt, outer_grad_state)
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 714, in __init__
    cnt, forward_index = forward_ctxt.AddForwardLoopCounter(outer_grad_state)
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2588, in AddForwardLoopCounter
    name="f_count")
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 245, in _Enter
    data, frame_name, is_constant, parallel_iterations, name=name)
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/tensorflow/python/ops/gen_control_flow_ops.py", line 219, in enter
    parallel_iterations=parallel_iterations, name=name)
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2043, in __init__
    self._control_flow_post_processing()
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2052, in _control_flow_post_processing
    control_flow_util.CheckInputFromValidContext(self, input_tensor.op)
  File "/root/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_util.py", line 350, in CheckInputFromValidContext
    raise ValueError(error_msg + " See info log for more details.")
ValueError: Cannot use 'training/while/gradients/f_count' as input to 'training/while/gradients/f_count_1' because they are in different while loops. See info log for more details.
```
Here is the code related to model building:

```python
>>  0 from tensorflow.keras import layers
    1 depth = args.depth
    2 input_dim = 76
    3 dropout = args.dropout
    4 rec_dropout = args.rec_dropout
    5 dim = args.dim
    6 X = layers.Input(shape=(None, input_dim), name='X')
    7 inputs = [X]
    8 mX = layers.Masking()(X)
    9 for i in range(depth-1):
   10     num_units = dim // 2
   11     lstm = layers.LSTM(units=num_units,
   12                        activation='tanh',
   13                        return_sequences=True,
   14                        recurrent_dropout=rec_dropout,
   15                        dropout=dropout)
   16     mx = layers.Bidirectional(lstm)(mX)
   17 L = layers.LSTM(units=dim,
   18                 activation='tanh',
   19                 return_sequences=False,
   20                 dropout=dropout,
   21                 recurrent_dropout=rec_dropout)(mx)
   22 L = layers.Dropout(dropout)(L)
   23 y = layers.Dense(1, activation='sigmoid')(L)
   24 outputs = [y]
   25 model = tf.keras.Model(inputs=inputs, outputs=outputs)
   26
   27 suffix = "{}.bs{}{}{}.ts{}{}".format(".dp" if args.use_dp else "",
>> 28                                    args.batch_size,
>> 29                                    ".L1{}".format(args.l1) if args.l1 > 0 else "",
>> 30                                    ".L2{}".format(args.l2) if args.l2 > 0 else "",
>> 31                                    args.timestep,
>> 32                                    ".trc{}".format(args.target_repl_coef) if args.target_repl_coef > 0 else "")
   33 # model.final_name = args.prefix + model.say_name() + suffix
   34 model.final_name = args.prefix + "k_lstm" + suffix
   35 print("==> model.final_name:", model.final_name)

```

and this is the dp-optimizer part:
```python
   23     print ("Use dpSGD...")
   22     optimizer = DPGradientDescentGaussianOptimizer(
   21                     l2_norm_clip=args.l2_norm_clip,
   20                     noise_multiplier=args.noise_multiplier,
>> 19                     num_microbatches=args.batch_size if args.microbatches==-1 else args.microbatches,
   18                     learning_rate=args.lr)
   17     # Compute vector of per-example loss rather than its mean over a minibatch.
   16     loss = tf.keras.losses.BinaryCrossentropy(
   15                     from_logits=True, reduction=tf.losses.Reduction.NONE)
   14     model.compile(optimizer=optimizer,
   13                   loss=loss)
   12     model.summary()

```

**Comment by minxueric** [comment]
Seems that I should use tf.Keras instead.

**Comment by minxueric** [comment]
I also tried not using tf.keras, namely defining `vector_loss` and the dp_optimizer. In this way, the tf.estimator will also generate similar error message.

**Comment by npapernot** [comment]
I would recommend trying to train your model with TF rather than Keras. Perhaps this tutorial can help? https://github.com/tensorflow/privacy/blob/master/tutorials/lm_dpsgd_tutorial.py

**Comment by minxueric** [comment]
Thank you for your reply!

I did solve this problem by training the model with TF rather than Keras.
