### ISSUE TITLE
Python3 tutorial: TypeError

### ISSUE THREAD

**Issue by bergen** [tensorflow/privacy#7]
There is a new issue after applying the fix in https://github.com/tensorflow/privacy/issues/4 . After finishing the first epoch:

```
Test accuracy after 1 epochs is: 0.715
Traceback (most recent call last):
  File "mnist_dpsgd_tutorial.py", line 184, in <module>
    tf.app.run()
  File "/home/leon/anaconda3/envs/privacy2/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "mnist_dpsgd_tutorial.py", line 178, in main
    eps = compute_epsilon(epoch * steps_per_epoch)
  File "mnist_dpsgd_tutorial.py", line 156, in compute_epsilon
    orders = [1 + x / 10. for x in range(1, 100)] + range(12, 64)
TypeError: can only concatenate list (not "range") to list
```

Edit: There's a PR for this: https://github.com/tensorflow/privacy/pull/3

**Comment by npapernot** [comment]
Closed by #3
