### ISSUE TITLE
Python3 rdp_accountant: "name 'long' is not defined"

### ISSUE THREAD

**Issue by bergen** [tensorflow/privacy#8]
rdp_accountant.py contains an assert statement `assert isinstance(alpha, (int, long))`. However, Python3 doesn't have a `long` type anymore.

Error message:
```
Traceback (most recent call last):
  File "mnist_dpsgd_tutorial.py", line 184, in <module>
    tf.app.run()
  File "/home/leon/anaconda3/envs/privacy2/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "mnist_dpsgd_tutorial.py", line 178, in main
    eps = compute_epsilon(epoch * steps_per_epoch)
  File "mnist_dpsgd_tutorial.py", line 161, in compute_epsilon
    orders=orders)
  File "/home/leon/Ferrum/machine_learning_prototypes/privacy_prototype/privacy/privacy/analysis/rdp_accountant.py", line 261, in compute_rdp
    for order in orders])
  File "/home/leon/Ferrum/machine_learning_prototypes/privacy_prototype/privacy/privacy/analysis/rdp_accountant.py", line 261, in <listcomp>
    for order in orders])
  File "/home/leon/Ferrum/machine_learning_prototypes/privacy_prototype/privacy/privacy/analysis/rdp_accountant.py", line 240, in _compute_rdp
    return _compute_log_a(q, sigma, alpha) / (alpha - 1)
  File "/home/leon/Ferrum/machine_learning_prototypes/privacy_prototype/privacy/privacy/analysis/rdp_accountant.py", line 145, in _compute_log_a
    return _compute_log_a_int(q, sigma, int(alpha))
  File "/home/leon/Ferrum/machine_learning_prototypes/privacy_prototype/privacy/privacy/analysis/rdp_accountant.py", line 89, in _compute_log_a_int
    assert isinstance(alpha, (int, long))
NameError: name 'long' is not defined
```

Edit: Looks like there's a PR for this: https://github.com/tensorflow/privacy/pull/1

**Comment by npapernot** [comment]
Closed by #1
